name: Track File Metadata (Detailed Log)

on:
  push:
    branches:
      - main

jobs:
  log-file-metadata:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup environment
        run: |
          mkdir -p metadata
          # If the metadata.json file doesn't exist, create it as an empty JSON object '{}'
          if [ ! -f metadata/metadata.json ]; then
            echo '{}' > metadata/metadata.json
          fi

      - name: Detect changed files
        id: changed
        run: |
          git diff-tree --no-commit-id --name-only -r ${{ github.sha }} > changed_files.txt
          echo "files=$(cat changed_files.txt | jq -R -s -c 'split("\n")[:-1]')" >> $GITHUB_OUTPUT

      - name: Update metadata.json
        run: |
          TIMESTAMP=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
          PR_TITLE="${{ github.event.pull_request.title }}"
          cp metadata/metadata.json metadata/_temp.json || echo '{}' > metadata/_temp.json

          while IFS= read -r FILE; do
            if [ -f "$FILE" ]; then
              SIZE=$(stat -c %s "$FILE")
              jq \
                --arg file "$FILE" \
                --arg date "$TIMESTAMP" \
                --arg title "$PR_TITLE" \
                --argjson size "$SIZE" \
                '.[$file] += [{"date": $date, "title": $title, "size": $size}] // {($file): [{"date": $date, "title": $title, "size": $size}]}' \
                metadata/_temp.json > metadata/_new.json && mv metadata/_new.json metadata/_temp.json
            fi
          done < changed_files.txt
          cat metadata/_temp.json | jq 'with_entries(select(.value | length > 0))' > metadata/_new.json
          mv metadata/_temp.json metadata/metadata.json

      - name: Commit and push metadata
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git remote set-url origin https://github.com/MarufHasan24/reasearch.git
          git add metadata/metadata.json
          git commit -m "📈 Update metadata.json with file change history" || echo "No changes to commit"
          git push https://x-access-token:$secrets.GH_TOKEN@github.com/MarufHasan24/reasearch.git HEAD:main
